### ISSUE TITLE
"The client has already been terminated." -error in `userInfoC.test.js`

### ISSUE THREAD

**Issue by akauppi** [akauppi/firebase-jest-testing#7]
```
$ npm test
...
  '/userInfo' rules
    ✓ no-one should be able to read (539 ms)
    ✕ only the user themselves can write the info (289 ms)

  ● '/userInfo' rules › only the user themselves can write the info

     [FirebaseError: [code=permission-denied]: 7 PERMISSION_DENIED: 
    false for 'create' @ L322]

      44 |     await Promise.all([
      45 |       expect(unauth_userinfoC.doc("abc").set(template)).toDeny(),   // unauthenticated
    > 46 |       expect(abc_userinfoC.doc("abc").set(template)).toAllow(),     // user themselves
         |                                                      ^
      47 |       expect(def_userinfoC.doc("abc").set(template)).toDeny(),     // another user
      48 |     ]);
      49 |

      at Object.<anonymous> (userInfoC.test.js:46:54)

  console.error
    UNEXPECTED exception within Firebase operation: Error [FirebaseError]: The client has already been terminated.
        at new FirestoreError (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/util/error.ts:217:5)
        at FirestoreClient.Object.<anonymous>.FirestoreClient.verifyNotTerminated (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/core/firestore_client.ts:154:13)
        at ensureFirestoreConfigured (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/database.ts:166:31)
        at executeWrite (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/reference_impl.ts:768:18)
        at setDoc (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/reference_impl.ts:288:10)
        at DocumentReference$1.Object.<anonymous>.DocumentReference$1.set (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/api/database.ts:733:14)
        at /Users/asko/Git/firebase-jest-testing/src/firestoreReadOnly/emul.js:39:60
        at /Users/asko/Git/firebase-jest-testing/src/firestoreReadOnly/emul.js:76:20
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
        at lockable (/Users/asko/Git/firebase-jest-testing/src/firestoreReadOnly/tools/lockable.js:56:12) {
      code: 'failed-precondition',
      toString: [Function (anonymous)]
    }
```

Clearly something that can be fixed. Likely related to the Jest 27 changes.

**Comment by akauppi** [comment]
No longer using Firebase client (0.0.3-alpha.2) so closing.
