### ISSUE TITLE
The `userInfo` test failing

### ISSUE THREAD

**Issue by akauppi** [akauppi/firebase-jest-testing#8]
```
 FAIL  sample/test-rules/userInfoC.test.js
  '/userInfo' rules
    ✓ no-one should be able to read (143 ms)
    ✕ only the user themselves can write the info (189 ms)

  ● '/userInfo' rules › only the user themselves can write the info

     [FirebaseError: [code=permission-denied]: 7 PERMISSION_DENIED: 
    false for 'create' @ L322]

      44 |     await Promise.all([
      45 |       expect(unauth_userinfoC.doc("abc").set(template)).toDeny(),   // unauthenticated
    > 46 |       expect(abc_userinfoC.doc("abc").set(template)).toAllow(),     // user themselves
         |                                                      ^
      47 |       expect(def_userinfoC.doc("abc").set(template)).toDeny(),     // another user
      48 |     ]);
      49 |

      at Object.<anonymous> (userInfoC.test.js:46:54)

  console.error
    UNEXPECTED exception within Firebase operation: Error [FirebaseError]: The client has already been terminated.
        at new FirestoreError (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/util/error.ts:217:5)
        at FirestoreClient.Object.<anonymous>.FirestoreClient.verifyNotTerminated (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/core/firestore_client.ts:154:13)
        at ensureFirestoreConfigured (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/database.ts:167:31)
        at executeWrite (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/reference_impl.ts:771:18)
        at setDoc (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/exp/reference_impl.ts:288:10)
        at DocumentReference$1.Object.<anonymous>.DocumentReference$1.set (/Users/asko/Git/firebase-jest-testing/node_modules/@firebase/firestore/src/api/database.ts:723:14)
        at /Users/asko/Git/firebase-jest-testing/src/firestoreReadOnly/emul.js:39:60
        at /Users/asko/Git/firebase-jest-testing/src/firestoreReadOnly/emul.js:76:20
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:94:5) {
      code: 'failed-precondition',
      toString: [Function (anonymous)]
    }
```

This started failing at some point (past 0.0.2-beta.2). Check why, try to bring back alive.

**Comment by akauppi** [comment]
Solved. Not sure what had caused it - or what fixed it.
